=== ansarifirdosh/Online-Gift-card-store/20048890 Firdosh Ansari Jawed Code/catalog_20048890.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!--STORE-->
    <xs:element name="store">
    
        <xs:complexType>
            <xs:sequence>
                <!--STORE DETAILS-->
                <xs:element name="storeDetails">
                    <!--STORE DETAILS ELEMENTS-->
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="logo"/>
                            <xs:element type="xs:string" name="storeName"/> 
                            <xs:element type="xs:string" name="description"/>
                            <xs:element type="xs:string" name="aboutUs"/>
                        </xs:sequence>
                    </xs:complexType>        
                </xs:element>

                <!--cardS-->
                <xs:element name="cards"> 
                    <xs:complexType>
                        <xs:sequence>
                            <!--card-->
                            <xs:element name="card" maxOccurs="unbounded" minOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="cardTitle"/>
                                        <!--card DESCRIPTION-->
                                        <xs:element name="cardDescription">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="cardCover">
                                                        <xs:complexType>
                                                                <xs:simpleContent>
                                                                    <xs:extension base="xs:string">
                                                                        <xs:attribute type="xs:string" name="coverID" use="optional"/>
                                                                    </xs:extension>
                                                                </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element type="xs:string" name="Name"/>
                                                    <xs:element type="xs:string" name="Issue-Date" maxOccurs="1" minOccurs="0"/>
                                                    <xs:element type="xs:float" name="Validity"/>
                                                    <xs:element type="xs:string" name="language" maxOccurs="1" minOccurs="0"/>
                                                    <xs:element type="xs:string" name="ratings"/>
                                                    <xs:element name="cost">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute type="xs:string" name="discount" use="optional"/>
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <!--AdditionalDetails-->
                                        <xs:element name="AdditionalDetails">
                                            <xs:complexType>
                                                 <xs:sequence> 
                                                    <xs:element name="PlaceUsed">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute name="PlaceUsedID" use="required">  
                                                                        <xs:simpleType>
                                                                            <xs:restriction base="xs:string">
                                                                                <xs:pattern value="[S][G][0-9][0-9][G]"/>
                                                                            </xs:restriction>
                                                                        </xs:simpleType>
                                                                    </xs:attribute> 
                                                                    <xs:attribute type="xs:string" name="location" use="optional"/>
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                      <xs:element name="items" maxOccurs="unbounded" minOccurs="0"> 
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute name="items" use="required">
                                                                        <xs:simpleType>
                                                                            <xs:restriction base="xs:string">
                                                                                <xs:pattern value="[S][G][0-9][0-9][G]"/>
                                                                            </xs:restriction>
                                                                        </xs:simpleType>
                                                                    </xs:attribute> 
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element> 
                                                    <xs:element type="xs:string" name="designer" maxOccurs="unbounded" minOccurs="1"/>
                                                    <xs:element type="xs:string" name="NoofUsers" maxOccurs="unbounded" minOccurs="0"/> 
                                                    <xs:element type="xs:string" name="Code" maxOccurs="unbounded" minOccurs="0"/>
                                                    <xs:element type="xs:string" name="discount" maxOccurs="unbounded" minOccurs="0"/>
                                                    <xs:element type="xs:string" name="availableItems" maxOccurs="unbounded" minOccurs="0"/>
                                                    <xs:element type="xs:string" name="bonus" maxOccurs="unbounded" minOccurs="0"/>
                                                    <xs:element type="xs:string" name="AuthorizedBy" maxOccurs="unbounded" minOccurs="0"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute  name="cardID" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute type="xs:string" name="type"/>
                                    <xs:attribute type="xs:string" name="length" use="optional"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <!--FOOTER-->
                <xs:element name="footer">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="footerLogo"/>
                            <!--CONTACT DETAILS-->
                            <xs:element name="contactDetails">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="address"/>                      
                                        <xs:element type="xs:string" name="phoneNumber" maxOccurs="unbounded" minOccurs="1"/>
                                        <xs:element type="xs:string" name="email"/>
                                        <xs:element type="xs:string" name="url"/>
                                        <!-- <xs:element type="xs:string" name="fact"/> -->
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element type="xs:string" name="copyright"/>                
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ansarifirdosh/Online-Gift-card-store/20048890 Firdosh Ansari Jawed Code/catalog_20048890.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<!--
Author: Firdosh Ansari Jawed
XML file
Ansari Giftcard Store
-->
  <?xml-stylesheet type="text/css" href="catalog_20048890.css"?>  
  <store xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Catalog_20048890.xsd" xmlns:xlink="http://www.w3.org/1999/xlink">  
	<storeDetails>
		<logo>
		</logo>
		<!-- the logo of store -->
		<storeName>
			Ansari Gift Card
		</storeName>
		<!-- The gift store is name Ansari Gift Store -->
		<description>
			&#xA; Since 2009
		</description>
		<!-- short description of the store -->
		<aboutUs>
			Ansari Gift card is a store in London, United Kingdom sells digital gift cards or gift vouchers. A gift card is 
            a form of payment that can be used to make purchases at retail stores, gas stations, 
            restaurants and other locations. You load money onto the card, which you or the gift 
            card recipient can then spend at accepted locations. 
		</aboutUs>
	</storeDetails>
	<!-- all card details -->
	<cards>
		<!-- Display for card 1 -->
		<card cardID="SN01" type="Best Deal">
			<cardTitle>
				Groetjet Sint 
			</cardTitle>
			<cardDescription>
				<cardCover coverID="F1">
				</cardCover>
				<Name>
				Sinketerklaas choice	
				</Name>
				<Issue-Date>
					2011-1-1
				</Issue-Date>
				<Validity>
					3
				</Validity>
				<language>
					English
				</language>
				<ratings>
					8/10
				</ratings>
				<cost>
					$ 450
				</cost>
			</cardDescription>
			<AdditionalDetails>
				<PlaceUsed PlaceUsedID="SG07G" location="London">
				    London
				</PlaceUsed>
				<designer>
					Aditya Pradhan
				</designer>
				<NoofUsers>
					103
				</NoofUsers>
				<Code>
					TWTWTSDHHFT
				</Code>
				<discount>
					5%
				</discount>
				<availableItems>
					330
				</availableItems>
				<!-- <bonus>
					$ 5
				</bonus> -->
			</AdditionalDetails>
		</card>
		<!-- Display for card 2 -->
		<card cardID="SN02" type="Offer">
			<cardTitle>
				Efterling
			</cardTitle>
			<cardDescription>
				<cardCover coverID="F2">
				</cardCover>
				<Name>
					Animal tree
				</Name>
				<Issue-Date>
					2011-12-1
				</Issue-Date>
				<Validity>
					2
				</Validity>
				<language>
					English
				</language>
				<ratings>
					4/5
				</ratings>
				<cost>
					$ 40
				</cost>
			</cardDescription>
			<AdditionalDetails>
				<PlaceUsed PlaceUsedID="SG03G" location="UK">
					London
				</PlaceUsed>
				<designer>
					Issac bott
				</designer>
				<NoofUsers>
					232
				</NoofUsers>
				<Code>
					ASDRFGGGFK
				</Code>
				<discount>
					5%
				</discount>
				<availableItems>
					120
				</availableItems>
				<bonus>
					$ 5
				</bonus>
			</AdditionalDetails>
		</card>
		<!-- Display for card 3 -->
		<card cardID="SN03" type="special">
			<cardTitle>
				Valentine Special
			</cardTitle>
			<cardDescription>
				<cardCover coverID="F3">
				</cardCover>
				<Name>
					Fijne Valentijn
				</Name>
				<Issue-Date>
					2009-07-09
				</Issue-Date>
				<Validity>
					5
				</Validity>
				<language>
					English
				</language>
				<ratings>
					09/10
				</ratings>
				<cost discount="10%">
					$ 50
				</cost>
			</cardDescription>
			<AdditionalDetails>
				<PlaceUsed PlaceUsedID="SG08G" location="UK">
					London
				</PlaceUsed>
				<designer>
					Ligal Thapa
				</designer>
				<NoofUsers>
					798
				</NoofUsers>
				<Code>
					CFDDRTGGH
				</Code>
				<discount>
					9%
				</discount>
				<availableItems>
					295
				</availableItems>
				<bonus>
					$ 15
				</bonus>
			</AdditionalDetails>
		</card>
		<!-- Display for card 4 -->
		<card cardID="SN04" type="Best Deal">
			<cardTitle>
				Nike Special
			</cardTitle>
			<cardDescription>
				<cardCover coverID="F4">
				</cardCover>
				<Name>
					Right tag
				</Name>
				<Issue-Date>
					2013-09-13
				</Issue-Date>
				<Validity>
					1
				</Validity>
				<language>
					French
				</language>
				<ratings>
					7/10
				</ratings>
				<cost>
					$30
				</cost>
			</cardDescription>
			<AdditionalDetails>
				<PlaceUsed PlaceUsedID="SG02G" location="London">
					London
				</PlaceUsed>
				<designer>
					Bruno Mars
				</designer>
				<NoofUsers>
					Shampoo Press Curl
				</NoofUsers>
				<Code>
					The Stereotypes
				</Code>
				<discount>
					5%
				</discount>
				<availableItems>
					33
				</availableItems>
				<bonus>
					$ 5
				</bonus>
			</AdditionalDetails>
		</card>
		<!-- Display for card 5 -->
		<card cardID="SN05" type="Best Deal">
			<cardTitle>
				Keuze cadeaukaart
			</cardTitle>
			<cardDescription>
				<cardCover coverID="F5">
				</cardCover>
				<Name>
					Keuze lanban
				</Name>
				<Validity>
					3
				</Validity>
				<language>
					Spanish
				</language>
				<ratings>
					3/5
				</ratings>
				<cost discount="10%">
					$ 43
				</cost>
			</cardDescription>
			<AdditionalDetails>
				<PlaceUsed PlaceUsedID="SG01G" location="Edinburg">
					Edinburg
				</PlaceUsed>
				<designer>
					Roshan Koirala
				</designer>
				<NoofUsers>
					987
				</NoofUsers>
				<Code>
					JFUFHFNVNVNH
				</Code>
				<discount>
				No
				</discount>
				<availableItems>
					49
				</availableItems>
				<bonus>
					$ 2
				</bonus>
			</AdditionalDetails>
		</card>
		<!-- Display for card 6 -->
		<card cardID="SN06" type="Offer">
			<cardTitle>
				Dagje Uit
			</cardTitle>
			<cardDescription>
				<cardCover coverID="F6">
				</cardCover>
				<Name>
					Cadehukaart
				</Name>
				<Issue-Date>
					2012-01-23
				</Issue-Date>
				<Validity>
					2
				</Validity>
				<language>
					Spanish
				</language>
				<ratings>
					4.8/5
				</ratings>
				<cost discount="5%">
					$ 6
				</cost>
			</cardDescription>
			<AdditionalDetails>
				<PlaceUsed PlaceUsedID="SG09G" location="Manchester">
					Manchester
				</PlaceUsed>
				<designer>
					Nikhil shrestha
				</designer>
				<NoofUsers>
					450
				</NoofUsers>
				<Code>
					KKGUHHGNGHG
				</Code>
				<discount>
					$ 0 
				</discount>
				<availableItems>
					239
				</availableItems>
				<bonus>
					$ 5
				</bonus>
			</AdditionalDetails>
		</card>
		<!-- Display for card 6 -->
		<card cardID="SN06" type="Best Deal">
			<cardTitle>
				Nationale Tuinob
			</cardTitle>
			<cardDescription>
				<cardCover coverID="F7">
				</cardCover>
				<Name>
					Alternative baffty
				</Name>
				<Issue-Date>
					2011-09-09
				</Issue-Date>
				<Validity>
					1
				</Validity>
				<language>
					English
				</language>
				<ratings>
					4.5/5
				</ratings>
				<cost>
					$ 70
				</cost>
			</cardDescription>
			<AdditionalDetails>
				<PlaceUsed PlaceUsedID="SG08G" location="London">
					London
				</PlaceUsed>
				<designer>
					Naony Tuinob
				</designer>
				<NoofUsers>
					245
				</NoofUsers>
				<Code>
					FGGTHUUUJML
				</Code>
				<discount>
					$ 6
				</discount>
				<availableItems>
					332
				</availableItems>
				<bonus>
					$ 15
				</bonus>
			</AdditionalDetails>
		</card>
		<!-- Display for card 8 -->
		<card cardID="SN08" type="Offer">
			<cardTitle>
				Jewel card
			</cardTitle>
			<cardDescription>
				<cardCover coverID="F8">
				</cardCover>
				<Name>
					Sieraden and horlo
				</Name>
				<Issue-Date>
					2012-11-03
				</Issue-Date>
				<Validity>
					3
				</Validity>
				<ratings>
					4/5
				</ratings>
				<cost discount="20%">
					$ 50
				</cost>
			</cardDescription>
			<AdditionalDetails>
				<PlaceUsed PlaceUsedID="SG05G" location="London">
					London
				</PlaceUsed>
				<designer>
					Abishek Jha
				</designer>
				<NoofUsers>
					345
				</NoofUsers>
				<Code>
					HGIGMBHGGMGNHG
				</Code>
				<discount>
					$ 5
				</discount>
				<availableItems>
					299
				</availableItems>
				<bonus>
					$ 0
				</bonus>
			</AdditionalDetails>
		</card>
		<!-- Display for card 9 -->
		<card cardID="SN09" type="Best Deal">
			<cardTitle>
				Romantisch Dineren
			</cardTitle>
			<cardDescription>
				<cardCover coverID="F9">
				</cardCover>
				<Name>
					Voor To personen
				</Name>
				<Issue-Date>
					2011-01-23
				</Issue-Date>
				<Validity>
					2
				</Validity>
				<language>
					English
				</language>
				<ratings>
					4/5
				</ratings>
				<cost>
					$ 60
				</cost>
			</cardDescription>
			<AdditionalDetails>
				<PlaceUsed PlaceUsedID="SG15G" location="Bristol">
					Bristol
				</PlaceUsed>
				<designer>
					Alin Bastola
				</designer>
				<NoofUsers>
					786
				</NoofUsers>
				<Code>
					HJUTGMKLOTY
				</Code>
				<discount>
					$2
				</discount>
				<availableItems>
					352
				</availableItems>
				<bonus>
					$ 7
				</bonus>
			</AdditionalDetails>
		</card>
		<!-- Display for card 10 -->
		<card cardID="SN10" type="Offer">
			<cardTitle>
				REIS CADEAU
			</cardTitle>
			<cardDescription>
				<cardCover coverID="F10">
				</cardCover>
				<Name>
					Journey Dewnlo
				</Name>
				<Issue-Date>
					2012-03-04
				</Issue-Date>
				<Validity>
					2
				</Validity>
				<language>
					French
				</language>
				<ratings>
					4.3/5
				</ratings>
				<cost discount="10%">
					$ 70
				</cost>
			</cardDescription>
			<AdditionalDetails>
				<PlaceUsed PlaceUsedID="SG02G" location="London">
					London
				</PlaceUsed>
				<designer>
					Kamil janin
				</designer>
				<NoofUsers>
					456
				</NoofUsers>
				<Code>
					KJDYDBHCYF
				</Code>
				<discount>
					$ 5
